import { useState } from "react";
import { Header } from "@/components/Header";
import { Hero } from "@/components/Hero";
import { HowItWorks } from "@/components/HowItWorks";
import { SummaryInput } from "@/components/SummaryInput";
import { SummaryDisplay, type PediatricSummary } from "@/components/SummaryDisplay";
import { Quiz } from "@/components/Quiz";
import { PDFExport } from "@/components/PDFExport";
import { Footer } from "@/components/Footer";
import { useToast } from "@/hooks/use-toast";

type AppState = "landing" | "input" | "summary" | "quiz" | "export";

interface QuizAnswer {
  questionId: string;
  answer: string;
  isCorrect: boolean;
  feedback: string;
}

// Mock AI processing - in production this would call your backend
const mockProcessSummary = async (text: string): Promise<PediatricSummary> => {
  // Simulate processing time
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  // Return a structured summary based on the input
  // In production, this would be generated by an LLM
  return {
    simpleExplanation: "Your child was seen for an ear infection (otitis media). This is a common childhood illness where fluid builds up behind the eardrum and becomes infected. It's typically caused by bacteria or viruses following a cold. While uncomfortable, ear infections usually respond well to treatment.",
    whatToDo: [
      "Give the prescribed antibiotic exactly as directed, completing the full course even if your child feels better",
      "Use children's acetaminophen or ibuprofen for pain and fever as needed",
      "Apply a warm compress to the affected ear for comfort",
      "Encourage rest and plenty of fluids",
      "Keep follow-up appointment in 2 weeks to ensure the infection has cleared"
    ],
    whatNotToDo: [
      "Don't put anything inside the ear canal",
      "Don't give aspirin to children",
      "Don't skip antibiotic doses or stop early",
      "Don't allow water to enter the ear while bathing until cleared by doctor"
    ],
    redFlags: [
      "Fever above 102°F (39°C) that doesn't respond to medication",
      "Severe or worsening ear pain despite pain medication",
      "Fluid or pus draining from the ear",
      "Redness or swelling behind the ear",
      "Your child becomes unusually drowsy or difficult to wake",
      "Stiff neck or severe headache",
      "Your child appears seriously ill or you're worried"
    ],
    medications: [
      {
        name: "Amoxicillin",
        dose: "250mg (5ml)",
        timing: "Three times daily with food",
        notes: "Complete the full 10-day course. Refrigerate the liquid. Shake well before each dose."
      },
      {
        name: "Children's Ibuprofen",
        dose: "100mg (5ml)",
        timing: "Every 6-8 hours as needed for pain or fever",
        notes: "Give with food to prevent stomach upset. Don't exceed 4 doses in 24 hours."
      }
    ],
    followUp: [
      "Schedule follow-up appointment with pediatrician in 2 weeks",
      "Call if symptoms don't improve within 48-72 hours of starting antibiotic",
      "Hearing test may be recommended if fluid persists"
    ],
    expectedCourse: "Your child should start feeling better within 48-72 hours of starting the antibiotic. Fever typically resolves within 24-48 hours. Some ear discomfort may continue for 2-3 days. It's normal for your child to be fussy or have trouble sleeping the first night or two. If symptoms worsen or don't improve after 3 days, contact your healthcare provider."
  };
};

// Mock quiz grading - in production this would call your backend
const mockGradeAnswer = async (
  question: { correctAnswer: string; question: string },
  answer: string
): Promise<{ isCorrect: boolean; feedback: string }> => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  // Simple keyword matching for demo - production would use LLM
  const keywords = question.correctAnswer.toLowerCase().split(/[;,\s]+/);
  const answerLower = answer.toLowerCase();
  const matchedKeywords = keywords.filter(kw => kw.length > 3 && answerLower.includes(kw));
  
  const isCorrect = matchedKeywords.length >= Math.min(3, keywords.length / 3);
  
  return {
    isCorrect,
    feedback: isCorrect 
      ? "Great! You've correctly identified the key points."
      : `The key points to remember are: ${question.correctAnswer.split(';').slice(0, 2).join(', ')}. Try to include these in your answer.`
  };
};

const Index = () => {
  const [appState, setAppState] = useState<AppState>("landing");
  const [summary, setSummary] = useState<PediatricSummary | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isGrading, setIsGrading] = useState(false);
  const [quizScore, setQuizScore] = useState(0);
  const [quizAnswers, setQuizAnswers] = useState<QuizAnswer[]>([]);
  const { toast } = useToast();

  const handleGetStarted = () => {
    setAppState("input");
    setTimeout(() => {
      document.getElementById('tool')?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  };

  const handleSubmitSummary = async (text: string) => {
    setIsProcessing(true);
    try {
      const result = await mockProcessSummary(text);
      setSummary(result);
      setAppState("summary");
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (error) {
      toast({
        title: "Error processing summary",
        description: "Please try again. If the problem persists, check that you've pasted a complete discharge summary.",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleStartQuiz = () => {
    setAppState("quiz");
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleGradeAnswer = async (
    question: { correctAnswer: string; question: string },
    answer: string
  ) => {
    setIsGrading(true);
    try {
      return await mockGradeAnswer(question, answer);
    } finally {
      setIsGrading(false);
    }
  };

  const handleQuizComplete = (score: number, answers: QuizAnswer[]) => {
    setQuizScore(score);
    setQuizAnswers(answers);
    setAppState("export");
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleStartOver = () => {
    setSummary(null);
    setQuizScore(0);
    setQuizAnswers([]);
    setAppState("landing");
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="pt-16">
        {/* Landing State */}
        {(appState === "landing" || appState === "input") && (
          <>
            <Hero onGetStarted={handleGetStarted} />
            <HowItWorks />
            <SummaryInput onSubmit={handleSubmitSummary} isLoading={isProcessing} />
          </>
        )}

        {/* Summary State */}
        {appState === "summary" && summary && (
          <SummaryDisplay summary={summary} onStartQuiz={handleStartQuiz} />
        )}

        {/* Quiz State */}
        {appState === "quiz" && summary && (
          <Quiz 
            summary={summary} 
            onComplete={handleQuizComplete}
            isGrading={isGrading}
            onGradeAnswer={handleGradeAnswer}
          />
        )}

        {/* Export State */}
        {appState === "export" && summary && (
          <PDFExport 
            summary={summary}
            quizScore={quizScore}
            quizAnswers={quizAnswers}
            onStartOver={handleStartOver}
          />
        )}
      </main>

      <Footer />
    </div>
  );
};

export default Index;
