import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  CheckCircle, 
  XCircle, 
  ChevronRight, 
  Trophy,
  AlertTriangle
} from "lucide-react";
import type { PediatricSummary } from "./SummaryDisplay";

interface QuizAnswer {
  questionId: string;
  // Indexes of options the user selected
  selectedOptionIndexes: number[];
  // Fraction between 0 and 1 representing how much of the question they got right
  scoreFraction: number;
}

interface QuizProps {
  summary: PediatricSummary;
  onComplete: (score: number, answers: QuizAnswer[]) => void;
}

export function Quiz({ summary, onComplete }: QuizProps) {
  const [questions] = useState(() => {
    // Prefer quiz questions generated by the LLM
    if (summary.quizQuestions && summary.quizQuestions.length > 0) {
      return summary.quizQuestions;
    }

    // Fallback: no questions available
    return [] as NonNullable<PediatricSummary["quizQuestions"]>;
  });

  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<QuizAnswer[]>([]);
  const [selectedIndexes, setSelectedIndexes] = useState<number[]>([]);
  const [showFeedback, setShowFeedback] = useState(false);
  const [lastScoreFraction, setLastScoreFraction] = useState(0);

  const currentQuestion = questions[currentIndex];
  const isComplete = currentIndex >= questions.length;

  const toggleOption = (index: number) => {
    setSelectedIndexes((prev) =>
      prev.includes(index)
        ? prev.filter((i) => i !== index)
        : [...prev, index]
    );
  };

  const handleSubmitAnswer = () => {
    if (!currentQuestion) return;

    // If feedback is already shown, this click advances to the next question
    if (showFeedback) {
      setSelectedIndexes([]);
      setShowFeedback(false);
      setLastScoreFraction(0);
      setCurrentIndex(currentIndex + 1);
      return;
    }

    const correctSet = new Set(currentQuestion.correctOptionIndexes);
    const selectedSet = new Set(selectedIndexes);

    const numCorrectSelected = Array.from(selectedSet).filter((idx) =>
      correctSet.has(idx)
    ).length;

    const numIncorrectSelected = Array.from(selectedSet).filter(
      (idx) => !correctSet.has(idx)
    ).length;

    const totalCorrect = correctSet.size || 1;

    // Basic partial credit:
    // - Reward correct selections
    // - Penalize incorrect selections
    let raw = numCorrectSelected - numIncorrectSelected * 0.5;
    raw = Math.max(0, raw);
    const scoreFraction = Math.min(1, raw / totalCorrect);

    // Store the result for this question
    setAnswers([
      ...answers,
      {
        questionId: currentQuestion.id,
        selectedOptionIndexes: selectedIndexes,
        scoreFraction,
      },
    ]);

    // Show immediate feedback; next click will advance
    setLastScoreFraction(scoreFraction);
    setShowFeedback(true);
  };

  const calculateScore = () => {
    if (!questions || questions.length === 0) return 0;

    const totalWeight = questions.reduce(
      (sum, q) => sum + (q.weight ?? 1),
      0
    );

    const earnedWeight = answers.reduce((sum, a) => {
      const q = questions.find((q) => q.id === a.questionId);
      if (!q) return sum;
      const weight = q.weight ?? 1;
      return sum + weight * a.scoreFraction;
    }, 0);

    if (totalWeight === 0) return 0;
    return Math.round((earnedWeight / totalWeight) * 100);
  };

  // If there are no questions, short-circuit to completion with 100%
  if (questions.length === 0) {
    onComplete(100, []);
    return null;
  }

  if (isComplete) {
    const score = calculateScore();
    return (
      <section className="py-12 bg-cream">
        <div className="container px-4">
          <div className="max-w-2xl mx-auto">
            <Card variant="elevated" className="text-center">
              <CardContent className="py-12">
                <div className={`w-20 h-20 rounded-full mx-auto mb-6 flex items-center justify-center ${
                  score >= 70 ? 'bg-success/10' : 'bg-warning/10'
                }`}>
                  {score >= 70 ? (
                    <Trophy className="w-10 h-10 text-success" />
                  ) : (
                    <AlertTriangle className="w-10 h-10 text-warning" />
                  )}
                </div>

                <h2 className="text-3xl font-bold text-foreground mb-2">
                  Your Score: {score}/100
                </h2>
                <p className={`text-lg mb-8 ${score >= 70 ? 'text-success' : 'text-warning'}`}>
                  {score >= 70 
                    ? "Great job! You understand the key care instructions."
                    : "Review the summary again - some key points need attention."
                  }
                </p>

                {/* Answer Summary */}
                <div className="text-left space-y-4 mb-8">
                  {answers.map((answer, index) => (
                    <div
                      key={answer.questionId}
                      className={`p-4 rounded-xl border ${
                        answer.scoreFraction >= 0.75
                          ? "bg-success/5 border-success/20"
                          : answer.scoreFraction > 0
                          ? "bg-warning/5 border-warning/20"
                          : "bg-coral-light border-accent/20"
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        {answer.scoreFraction >= 0.75 ? (
                          <CheckCircle className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
                        ) : answer.scoreFraction > 0 ? (
                          <AlertTriangle className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
                        ) : (
                          <XCircle className="w-5 h-5 text-accent flex-shrink-0 mt-0.5" />
                        )}
                        <div>
                          <p className="font-medium text-foreground mb-1">
                            {questions[index]?.question}
                          </p>
                          <div className="text-sm text-muted-foreground space-y-1">
                            <p>
                              <span className="font-semibold">Your answer:</span>{" "}
                              {answer.selectedOptionIndexes
                                .map(
                                  (i) =>
                                    questions[index]?.options[i] ??
                                    `Option ${i + 1}`
                                )
                                .join("; ") || "No options selected"}
                            </p>
                            <p>
                              <span className="font-semibold">
                                Correct answer(s):
                              </span>{" "}
                              {questions[index]?.correctOptionIndexes
                                .map(
                                  (i) =>
                                    questions[index]?.options[i] ??
                                    `Option ${i + 1}`
                                )
                                .join("; ")}
                            </p>
                            {questions[index]?.explanation && (
                              <p className="italic">
                                {questions[index]?.explanation}
                              </p>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <Button 
                  variant="hero" 
                  size="xl"
                  onClick={() => onComplete(score, answers)}
                >
                  Continue to PDF Export
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="py-12 bg-cream">
      <div className="container px-4">
        <div className="max-w-2xl mx-auto">
          {/* Progress */}
            <div className="mb-8">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-muted-foreground">
                  Question {currentIndex + 1} of {questions.length}
                </span>
                <span
                  className={`text-xs px-2 py-1 rounded-full ${
                    currentQuestion?.category === "redFlag"
                      ? "bg-destructive/10 text-destructive"
                      : "bg-primary/10 text-primary"
                  }`}
                >
                  {currentQuestion?.category === "redFlag"
                    ? "⚠️ Safety Critical"
                    : currentQuestion?.category === "medication"
                    ? "💊 Medication"
                    : currentQuestion?.category === "followUp"
                    ? "📅 Follow-up"
                    : "🏥 Care"}
                </span>
              </div>
              <div className="h-2 bg-muted rounded-full overflow-hidden">
                <div
                  className="h-full bg-primary transition-all duration-300 rounded-full"
                  style={{
                    width: `${(currentIndex / questions.length) * 100}%`,
                  }}
                />
              </div>
            </div>

            <Card variant="elevated">
              <CardHeader>
                <CardTitle className="text-xl">
                  {currentQuestion?.question}
                </CardTitle>
                <CardDescription>
                  Select all answers that are correct based on the summary you
                  received.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {currentQuestion?.options.map((option, index) => {
                    const isSelected = selectedIndexes.includes(index);
                    const isCorrect =
                      currentQuestion?.correctOptionIndexes.includes(
                        index
                      ) ?? false;
                    return (
                      <button
                        key={index}
                        type="button"
                        onClick={() => {
                          if (!showFeedback) toggleOption(index);
                        }}
                        className={`w-full flex items-start gap-3 p-3 rounded-xl border text-left transition-colors ${
                          showFeedback
                            ? isCorrect
                              ? "border-success bg-success/5"
                              : isSelected
                              ? "border-accent bg-coral-light/40"
                              : "border-border bg-background"
                            : isSelected
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-primary/60"
                        }`}
                      >
                        <div
                          className={`mt-1 w-5 h-5 rounded border flex items-center justify-center ${
                            showFeedback
                              ? isCorrect
                                ? "bg-success border-success"
                                : isSelected
                                ? "bg-accent border-accent"
                                : "border-muted-foreground"
                              : isSelected
                              ? "bg-primary border-primary"
                              : "border-muted-foreground"
                          }`}
                        >
                          {isSelected && (
                            <CheckCircle className="w-4 h-4 text-primary-foreground" />
                          )}
                        </div>
                        <span className="text-sm text-foreground">
                          {option}
                        </span>
                      </button>
                    );
                  })}
                </div>

                {showFeedback && (
                  <div
                    className={`mt-4 p-4 rounded-xl border ${
                      lastScoreFraction >= 0.75
                        ? "bg-success/10 border-success/30"
                        : lastScoreFraction > 0
                        ? "bg-warning/10 border-warning/30"
                        : "bg-coral-light border-accent/30"
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      {lastScoreFraction >= 0.75 ? (
                        <CheckCircle className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
                      ) : lastScoreFraction > 0 ? (
                        <AlertTriangle className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
                      ) : (
                        <XCircle className="w-5 h-5 text-accent flex-shrink-0 mt-0.5" />
                      )}
                      <div className="text-sm text-foreground space-y-1">
                        <p className="font-semibold">
                          {lastScoreFraction >= 0.75
                            ? "Great job – you picked the key answers."
                            : lastScoreFraction > 0
                            ? "You picked some of the right answers, but missed a few important ones."
                            : "Those selections were not the ones listed in your child's instructions."}
                        </p>
                        {currentQuestion?.explanation && (
                          <p className="italic">
                            {currentQuestion.explanation}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                <div className="flex gap-3 pt-4">
                  <Button
                    variant="hero"
                    size="lg"
                    className="flex-1"
                    onClick={handleSubmitAnswer}
                    disabled={!showFeedback && selectedIndexes.length === 0}
                  >
                    {showFeedback ? "Next Question" : "Submit Answer"}
                    <ChevronRight className="w-4 h-4 ml-2" />
                  </Button>
                </div>
              </CardContent>
            </Card>
        </div>
      </div>
    </section>
  );
}
